trigger:
- master

name: $(Date:yyyyMMdd)$(Rev:.r)

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(build.sourcesDirectory)'
    TargetFolder: '$(build.ArtifactStagingDirectory)'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
